[pytest]
# Django 설정 파일 경로 (본인의 프로젝트 폴더명에 맞게 수정하세요)
DJANGO_SETTINGS_MODULE = config.settings

# 테스트 파일 탐색 규칙
python_files = tests.py test_*.py *_tests.py *_test.py

# 실행 옵션 (-s: print 허용, --strict-markers: 등록되지 않은 마커 제한)
addopts = -s --strict-markers --reuse-db