# Generated by Django 6.0.4 on 2026-04-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(help_text="댓글 내용", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "활성"), ("deleted", "삭제")],
                        default="ACTIVE",
                        help_text="상태(활성, 비활성화)",
                        max_length=20,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="삭제일", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글 목록",
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
            ],
            options={
                "verbose_name": "댓글 좋아요",
                "verbose_name_plural": "댓글 좋아요 목록",
                "db_table": "comment_likes",
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
            ],
            options={
                "verbose_name": "팔로우",
                "verbose_name_plural": "팔로우 목록",
                "db_table": "follows",
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
            ],
            options={
                "verbose_name": "게시글 좋아요",
                "verbose_name_plural": "게시글 좋아요 목록",
                "db_table": "post_likes",
            },
        ),
        migrations.CreateModel(
            name="ReportActions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("delete", "삭제"),
                            ("keep", "유지"),
                            ("ABUSE", "욕설/비하/혐오 표현"),
                            ("SPAM", "스팸/광고"),
                            ("FALSE_INFO", "허위정보"),
                            ("SEXUAL", "음란/선정적 컨텐츠"),
                            ("INAPPROPRIATE_PROFILE", "부적절한 닉네임/프로필"),
                            ("OTHER", "기타"),
                        ],
                        help_text="처분의내용",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
            ],
            options={
                "verbose_name": "신고 처리 이력",
                "verbose_name_plural": "신고 처리 이력 목록",
                "db_table": "report_actions",
            },
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_id", models.PositiveIntegerField(help_text="신고 대상의 ID")),
                (
                    "target_type",
                    models.CharField(
                        choices=[("POST", "게시글"), ("COMMENT", "댓글")],
                        help_text="신고 대상의 유형",
                        max_length=20,
                    ),
                ),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("abuse", "욕설/비하/혐오 표현"),
                            ("spam", "스팸/광고"),
                            ("false_info", "허위정보"),
                            ("sexual", "음란/선정적 컨텐츠"),
                            ("other", "기타"),
                        ],
                        help_text="신고 사유",
                        max_length=100,
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(
                        blank=True,
                        help_text="신고 사유 상세 설명",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("handled", "처리완료"),
                            ("dismissed", "기각"),
                        ],
                        default="PENDING",
                        help_text="신고의 처리 상태",
                        max_length=20,
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(blank=True, help_text="신고의 처리 일시", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
            ],
            options={
                "verbose_name": "신고",
                "verbose_name_plural": "신고 목록",
                "db_table": "reports",
            },
        ),
        migrations.CreateModel(
            name="Scrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "스크랩",
                "verbose_name_plural": "스크랩 목록",
                "db_table": "scraps",
            },
        ),
    ]
