# Generated by Django 6.0.4 on 2026-04-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("active", "활성"), ("deleted", "삭제")],
                default="active",
                max_length=20,
            ),
        ),
    ]
