# Generated by Django 6.0.4 on 2026-04-14 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("interactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="follower_user_id",
            field=models.ForeignKey(
                db_column="follower_id",
                help_text="팔로우를 하는 유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="팔로우하는유저id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="following_user_id",
            field=models.ForeignKey(
                db_column="following_id",
                help_text="팔로우를 받는 유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="팔로우받는유저id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower_user_id", "following_user_id")},
        ),
    ]
