# Generated by Django 6.0.4 on 2026-04-13 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("interactions", "0002_initial"),
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commentlike",
            name="comment",
            field=models.ForeignKey(
                db_column="comment_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="interactions.comment",
            ),
        ),
        migrations.AddField(
            model_name="commentlike",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="follower_user_id",
            field=models.ForeignKey(
                db_column="follower_id",
                help_text="팔로우를 하는 유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="팔로우하는유저id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="following_user_id",
            field=models.ForeignKey(
                db_column="following_id",
                help_text="팔로우를 받는 유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="팔로우받는유저id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                db_column="post_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postlike",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportactions",
            name="admin_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="처리한관리자ID",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reports",
            name="admin_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reports",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportactions",
            name="report_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="신고ID",
                to="interactions.reports",
            ),
        ),
        migrations.AddField(
            model_name="scrap",
            name="post",
            field=models.ForeignKey(
                db_column="post_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraps",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="scrap",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together={("comment", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower_user_id", "following_user_id")},
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together={("post", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="scrap",
            unique_together={("post", "user")},
        ),
    ]
