# Generated by Django 6.0.4 on 2026-04-28 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="question",
        ),
    ]
