# Generated by Django 6.0.4 on 2026-04-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "정상"),
                    ("suspended", "정지"),
                    ("restricted", "제한"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
