# Generated by Django 6.0.4 on 2026-04-14 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={"verbose_name": "팔로우", "verbose_name_plural": "팔로우 목록"},
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower_user_id", "following_user_id")},
        ),
        migrations.AddField(
            model_name="follow",
            name="follower_user_id",
            field=models.ForeignKey(
                db_column="follower_id",
                help_text="팔로우를 하는 유저",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="팔로우하는유저id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="following_user_id",
            field=models.ForeignKey(
                db_column="following_id",
                help_text="팔로우를 받는 유저",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="팔로우받는유저id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일"),
        ),
        migrations.RemoveField(
            model_name="follow",
            name="follower_user",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="following_user",
        ),
    ]
