# Generated by Django 6.0.4 on 2026-04-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_follow_options_alter_follow_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_image_url",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.CharField(
                choices=[
                    ("avatar_1", "캐릭터 1"),
                    ("avatar_2", "캐릭터 2"),
                    ("avatar_3", "캐릭터 3"),
                    ("avatar_4", "캐릭터 4"),
                ],
                default="avatar_1",
                max_length=20,
            ),
        ),
    ]
