# Generated by Django 6.0.4 on 2026-04-20 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_profile_image_url_user_profile_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
