# Generated by Django 6.0.4 on 2026-04-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
