# Generated by Django 6.0.4 on 2026-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_profile_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
