# Generated by Django 6.0.4 on 2026-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_social_profile_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="social_profile_image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
