# Generated by Django 6.0.4 on 2026-05-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_user_social_profile_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallogin",
            name="social_nickname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sociallogin",
            name="social_profile_image_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="social_profile_image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
