# Generated by Django 6.0.4 on 2026-04-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_id", models.BigIntegerField()),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("POST", "게시글"),
                            ("COMMENT", "댓글"),
                            ("USER", "유저"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason_type", models.CharField(max_length=100)),
                ("reason_detail", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("handled", "처리완료"),
                            ("dismissed", "기각"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reports",
            },
        ),
        migrations.CreateModel(
            name="ReportAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=30)),
                ("memo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "report_actions",
            },
        ),
    ]
