# Generated by Django 6.0.4 on 2026-04-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_id", models.BigIntegerField(help_text="신고 대상의 ID")),
                (
                    "target_type",
                    models.CharField(
                        choices=[("post", "게시글"), ("comment", "댓글")],
                        help_text="신고 대상의 유형",
                        max_length=20,
                    ),
                ),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("abuse", "욕설/비하/혐오 표현"),
                            ("spam", "스팸/광고"),
                            ("false_info", "허위정보"),
                            ("sexual", "음란/선정적 컨텐츠"),
                            ("other", "기타"),
                        ],
                        help_text="신고 사유",
                        max_length=100,
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(
                        blank=True,
                        help_text="신고 사유 상세 설명",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("handled", "처리완료"),
                            ("dismissed", "기각"),
                        ],
                        default="pending",
                        help_text="신고의 처리 상태",
                        max_length=20,
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(blank=True, help_text="신고의 처리 일시", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
            ],
            options={
                "verbose_name": "신고",
                "verbose_name_plural": "신고 목록",
                "db_table": "reports",
            },
        ),
        migrations.CreateModel(
            name="ReportAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(choices=[("delete", "삭제"), ("keep", "유지")], max_length=50),
                ),
                ("memo", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="신고의 처리 일시"),
                ),
            ],
            options={
                "verbose_name": "신고 처리 이력",
                "verbose_name_plural": "신고 처리 이력 목록",
                "db_table": "report_actions",
            },
        ),
    ]
