# Generated by Django 6.0.4 on 2026-04-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason_type",
            field=models.CharField(
                choices=[
                    ("ABUSE", "욕설/비하/혐오 표현"),
                    ("SPAM", "스팸/광고"),
                    ("FALSE_INFO", "허위정보"),
                    ("SEXUAL", "음란/선정적 컨텐츠"),
                    ("INAPPROPRIATE_PROFILE", "부적절한 닉네임/프로필"),
                    ("OTHER", "기타"),
                ],
                max_length=100,
            ),
        ),
    ]
