# Generated by Django 6.0.4 on 2026-04-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_alter_report_reason_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason_type",
            field=models.CharField(
                choices=[
                    ("ABUSE", "욕설/비하/혐오 표현"),
                    ("SPAM", "스팸/광고"),
                    ("FALSE_INFO", "허위정보"),
                    ("SEXUAL", "음란/선정적 컨텐츠"),
                    ("OTHER", "기타"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="target_type",
            field=models.CharField(choices=[("POST", "게시글"), ("COMMENT", "댓글")], max_length=10),
        ),
        migrations.AlterField(
            model_name="reportaction",
            name="action_type",
            field=models.CharField(choices=[("DELETE", "삭제"), ("KEEP", "유지")], max_length=30),
        ),
    ]
