# Generated by Django 6.0.4 on 2026-04-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_alter_report_reason_type_alter_report_target_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason_type",
            field=models.CharField(
                choices=[
                    ("abuse", "욕설/비하/혐오 표현"),
                    ("spam", "스팸/광고"),
                    ("false_info", "허위정보"),
                    ("sexual", "음란/선정적 컨텐츠"),
                    ("other", "기타"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="target_type",
            field=models.CharField(choices=[("post", "게시글"), ("comment", "댓글")], max_length=10),
        ),
        migrations.AlterField(
            model_name="reportaction",
            name="action_type",
            field=models.CharField(choices=[("delete", "삭제"), ("keep", "유지")], max_length=30),
        ),
    ]
