# Generated by Django 6.0.4 on 2026-04-14 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_alter_report_reason_type_alter_report_target_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"verbose_name": "신고", "verbose_name_plural": "신고 목록"},
        ),
        migrations.AlterModelOptions(
            name="reportaction",
            options={
                "verbose_name": "신고 처리 이력",
                "verbose_name_plural": "신고 처리 이력 목록",
            },
        ),
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일"),
        ),
        migrations.AlterField(
            model_name="report",
            name="handled_at",
            field=models.DateTimeField(blank=True, help_text="신고의 처리 일시", null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="reason_detail",
            field=models.TextField(blank=True, help_text="신고 사유 상세 설명", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="reason_type",
            field=models.CharField(
                choices=[
                    ("abuse", "욕설/비하/혐오 표현"),
                    ("spam", "스팸/광고"),
                    ("false_info", "허위정보"),
                    ("sexual", "음란/선정적 컨텐츠"),
                    ("other", "기타"),
                ],
                help_text="신고 사유",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기중"),
                    ("handled", "처리완료"),
                    ("dismissed", "기각"),
                ],
                default="pending",
                help_text="신고의 처리 상태",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="target_id",
            field=models.BigIntegerField(help_text="신고 대상의 ID"),
        ),
        migrations.AlterField(
            model_name="report",
            name="target_type",
            field=models.CharField(
                choices=[("post", "게시글"), ("comment", "댓글")],
                help_text="신고 대상의 유형",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정일"),
        ),
        migrations.AlterField(
            model_name="reportaction",
            name="action_type",
            field=models.CharField(choices=[("delete", "삭제"), ("keep", "유지")], max_length=50),
        ),
        migrations.AlterField(
            model_name="reportaction",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="처리한관리자ID",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reportaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="신고의 처리 일시"),
        ),
        migrations.AlterField(
            model_name="reportaction",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="신고ID",
                to="reports.report",
            ),
        ),
    ]
