# Generated by Django 6.0.4 on 2026-04-14 07:21

from django.db import migrations, models

import apps.posts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(help_text="댓글 내용", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "활성"), ("deleted", "삭제")],
                        default="CommentStatus.ACTIVE",
                        help_text="상태(활성, 비활성화)",
                        max_length=20,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="삭제일", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글 목록",
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "댓글 좋아요",
                "verbose_name_plural": "댓글 좋아요 목록",
                "db_table": "comment_likes",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "images",
                    models.JSONField(
                        default=list,
                        help_text="게시글 이미지 URL 리스트(최대 3개)",
                        validators=[apps.posts.models.image_count],
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("goal_start_date", models.DateTimeField(blank=True, null=True)),
                ("goal_end_date", models.DateTimeField(blank=True, null=True)),
                ("goal_title", models.CharField(blank=True, max_length=255, null=True)),
                ("goal_progress", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("hidden", "숨김"),
                            ("reported", "신고됨"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "posts",
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
            ],
            options={
                "verbose_name": "게시글 좋아요",
                "verbose_name_plural": "게시글 좋아요 목록",
                "db_table": "post_likes",
            },
        ),
        migrations.CreateModel(
            name="PostTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "post_tags",
            },
        ),
        migrations.CreateModel(
            name="PostView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="조회 일시"),
                ),
            ],
            options={
                "verbose_name": "게시글 조회 기록",
                "db_table": "post_views",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="Scrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "스크랩",
                "verbose_name_plural": "스크랩 목록",
                "db_table": "scraps",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tags",
            },
        ),
    ]
