# Generated by Django 6.0.4 on 2026-04-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("normal", "정상"),
                    ("hidden", "숨김"),
                    ("reported", "신고됨"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
