# Generated by Django 6.0.4 on 2026-04-13 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="posttag",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_tags",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postview",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_logs",
                to="posts.post",
                verbose_name="조회 게시글",
            ),
        ),
        migrations.AddField(
            model_name="postview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="조회 유저",
            ),
        ),
        migrations.AddField(
            model_name="posttag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_tags",
                to="posts.tag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="posttag",
            unique_together={("post", "tag")},
        ),
    ]
