# Generated by Django 6.0.4 on 2026-04-13 04:34

from django.db import migrations, models

import apps.posts.models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.JSONField(
                default=list,
                help_text="게시글 이미지 URL 리스트(최대 3개)",
                validators=[apps.posts.models.image_count],
            ),
        ),
    ]
