# Generated by Django 6.0.4 on 2026-04-15 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_alter_tag_options_alter_tag_created_at_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "태그", "verbose_name_plural": "태그 목록"},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="post_id",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                db_column="post",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts.post",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                db_column="user",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("active", "활성"), ("deleted", "삭제")],
                default="active",
                help_text="상태(활성, 비활성화)",
                max_length=20,
            ),
        ),
    ]
