# Generated by Django 6.0.4 on 2026-04-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "check_goals",
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "진행중"),
                            ("failed", "미달성"),
                            ("completed", "완료"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "goals",
            },
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekly_rank", models.IntegerField(blank=True, null=True)),
                ("weekly_cert_count", models.IntegerField(blank=True, null=True)),
                ("monthly_rank", models.IntegerField(blank=True, null=True)),
                ("monthly_cert_count", models.IntegerField(blank=True, null=True)),
                ("total_rank", models.IntegerField(blank=True, null=True)),
                ("total_cert_count", models.IntegerField(blank=True, null=True)),
                ("total_goal_count", models.IntegerField(blank=True, null=True)),
                ("week_start", models.DateField(blank=True, null=True)),
                ("month_start", models.DateField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "rankings",
            },
        ),
        migrations.CreateModel(
            name="RoundGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_no", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "round_goals",
            },
        ),
    ]
